### ISSUE TITLE
End ServiceManager when  a specific Service stops

### ISSUE THREAD

**Issue by xavfernandez** [sileht/cotyledon#21]
Hello and thanks for this project.

I'd be interested in having a special flag to tell that a `Service` should not be restarted and should instead lead to the exit of the `ServiceManager`.

Would there be interest to include such feature to cotyledon ?
(To know if it is worth it to spend time on a PR or it has no chance of being merged :) )

**Comment by xavfernandez** [comment]
Thanks for the PR.

The `on_dead_worker` seems like an useful enhancement.

However the example does not work: killing the Service causes:
```
ERROR 2018-12-21T11:19:51.036513+01:00 cotyledon._utils Exception raised during dead_worker hooks
Traceback (most recent call last):
  File "/home/xfernandez/other_dev/cotyledon/cotyledon/_utils.py", line 87, in run_hooks
    hook(*args, **kwargs)
  File "/home/xfernandez/dev/foo/src/bar/runner.py", line 97, in on_dead_worker
    sm.shutdown()
  File "/home/xfernandez/other_dev/cotyledon/cotyledon/_service_manager.py", line 283, in shutdown
    signal.signal(signal.SIGTERM, signal.SIG_IGN)
  File "/usr/lib64/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

but,
```
    def on_dead_worker(service_id, worker_id, exit_code):
        # Shutdown manager if main_service_id died
        if service_id == main_service_id:
            os.kill(os.getpid(), signal.SIGINT)
```
does kill everything.

**Comment by sileht** [comment]
My last update shouold have fixed the race: 

https://github.com/sileht/cotyledon/commit/f92710c668ddc1131468cc6a2ce831877651a3d7#diff-76422174db92f696187cfee268f8831dL230

**Comment by xavfernandez** [comment]
However:

```
    def shutdown(self):
        LOG.error("manual shutdown")
        os.kill(os.getpid(), signal.SIGTERM)
        self._dead.wait()
```
prevents the race-condition :)

**Comment by sileht** [comment]
@xavfernandez great thx!

**Comment by xavfernandez** [comment]
Thanks for the PR :)

Any idead when this could get released ?

**Comment by sileht** [comment]
I made the release with this.

**Comment by xavfernandez** [comment]
> I made the release with this.

Thanks :)
