### ISSUE TITLE
Cannot SIGINT a service manager when ran through make

### ISSUE THREAD

**Issue by lburg** [sileht/cotyledon#26]
We're running a `ServiceManager` through a make command similar to this:

```python
run_server:
    python /path/to/server/run.py
```

Our `run.py` basically does this:

```python
p = cotyledon.ServiceManager()
p.add(...)
p.run()
```
However, calling `os.setsid` as done by the service manager(https://github.com/sileht/cotyledon/blob/master/cotyledon/_service_manager.py#L126-L130) renders pressing ctrl-c ineffective. Sending a SIGINT signal using kill to the make process doesn't stop the server. Sending SIGINT to the service manager process does interrupt it.

I'm not too familiar with how make handles signals, but according to [this coreutils issue](https://lists.gnu.org/archive/html/bug-coreutils/2011-06/msg00130.html), it seems that:

> What seems to be happening is that make *doesn't* create a process group,
> therefore assumes that when it gets a SIGINT, its children have already
> gotten it too, and it just waits for them to die. A child that puts itself
> into a new process group screws this up (as would kill -2 `pidof make`).

Creating a new session for cotyledon's service manager seems to break make's expectation of SIGINT propagating to its children.

Removing the call to `os.setsid` allows me to cancel the server launched by make using a SIGINT signal.

What do you think about this? Is creating a new session really useful? It seems not, as it gets ignored when unavaible (e.g.: when running on Windows).

**Comment by sileht** [comment]
That's the expected behavior. We use `os.killpg` to shutdown every child processes. Clean shutdown can't be done on Window, see https://cotyledon.readthedocs.io/en/latest/non-posix-support.html.
