### ISSUE TITLE
reconfigure workers based on a callback evaluated at intervals

### ISSUE THREAD

**Issue by buddiex** [sileht/cotyledon#43]
I want to start n workers and scale (reconfigure) them up/down based on number of task from a remote queue (access via REST api). How can I do this?

One suggestion is implementing `on_interal_eval`callback that runs a function at certain interval and can reconfigure the manager.

**Comment by sileht** [comment]
That's could be done outside the library, just call `ServiceManager.reconfigure()` when you want.
